name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11
      - name: Set up Node.js Engine
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
      - name: Install Dependencies
        run: pnpm install
      - name: Build Files
        run: pnpm -r build
      - name: Assemble Public Directory
        run: |
          mkdir -p dist
          cp -r main/dist/. dist/
          cp -r gff/dist dist/gff
          cp -r something/dist dist/something
      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
