name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js Engine
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install
      - name: Build Files
        run: yarn build
      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: main
