name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Base Deploy Directory
        run: mkdir -p dist
      - name: Set up Node.js Engine
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"
          cache-dependency-path: gff/yarn.lock
      - name: Main Install Dependencies
        run: |
          cd main
          yarn install
      - name: Main Build Files
        run: |
          cd main
          yarn build
      - name: GFF Install Dependencies
        run: |
          cd gff
          yarn install
      - name: GFF Build Files
        run: |
          cd gff
          yarn build
      - name: Something Install Dependencies
        run: |
          cd something
          yarn install
      - name: Something Build Files
        run: |
          cd something
          yarn build
      - name: Assemble Public Directory
        run: |
          mkdir -p dist
          cp -r ./main/dist/* ./dist/
          cp -r ./gff/dist ./dist/gff
          cp -r ./something/dist ./dist/something
      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
